version: '3'

services:
  meshtastic-map:
    container_name: meshmap
    restart: always
    image: meshtastic-map/core:dev
    # Enables the web UI and tells Traefik to listen to docker
    # command:
    #   - node 
    environment:
      - DATABASE_URL=mysql://root:${MARIADB_ROOT_PASSWORD}@meshmap-db:3306/meshtastic-map?connection_limit=100
      - MQTT_BROKER_URL="mqtt://mqtt.meshtastic.org"
      - MQTT_USERNAME="meshdev"
      - MQTT_PASSWORD="large4cats"
      - ADDITIONAL_MQTT_OPTION=""
    ports:
      # The HTTP port
      - "8080:8080"
    networks:
      - meshtastic_map
    depends_on:
      meshmap-db:
        condition: service_healthy


  meshmap-db:
    container_name: meshmap-db
    image: bitnami/mariadb:latest
    env_file:
      - .env
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - meshtastic_map
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

volumes:
  dbdata:
    driver: local

networks:
  meshtastic_map:
